# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/xenial64"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network "forwarded_port", guest: 5601, host: 5601, host_ip: "10.0.0.29"
    config.vm.network "forwarded_port", guest: 9200, host: 9200, host_ip: "10.0.0.29"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "10.0.2.15"

    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "4096"
    end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    wget -nv -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    sudo add-apt-repository -y ppa:webupd8team/java
    echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
    echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    apt-get update
    sudo apt-get -y -qq install oracle-java8-installer apt-transport-https elasticsearch kibana logstash

    sudo sed -i 's/#START_DAEMON/START_DAEMON/' /etc/default/elasticsearch
    sudo sed -i 's/#elasticsearch.url: \"http://localhost:9200\"/elasticsearch.url: "http://10.0.2.15:9200"/' /etc/kibana/kibana.yml
    sudo sed -i 's/#network.host: 192.168.0.1/network.host: 0.0.0.0/' /etc/elasticsearch/elasticsearch.yml
    sudo sed -i 's/#server.host: \"localhost\"/server.host: "0.0.0.0"/' /etc/kibana/kibana.yml

    sudo systemctl restart elasticsearch
    sudo systemctl restart kibana

    systemctl status elasticsearch
    systemctl status kibana
  SHELL
end
